version: '3'

services:
  database:
    image: mysql:5.7
    ports:
      - "3306:3307"
    environment:
      MYSQL_DATABASE: peopleflow
      MYSQL_USER: sa
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
  app:
    build: .
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database/peopleflow
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - database